const GET_USERS_DATA_INIT = "GET_USERS_DATA_INIT";
const GET_USERS_DATA_SUCCESS = "GET_USERS_DATA_SUCCESS";
const GET_USERS_DATA_ERROR = "GET_USERS_DATA_ERROR";

export {
  GET_USERS_DATA_INIT,
  GET_USERS_DATA_SUCCESS,
  GET_USERS_DATA_ERROR
};
